server:
  port: 9000
spring:
  application:
    name: dg-spring-boot-admin
    # 初期先使用用本地配置文件，稳定以后采用 config
  cloud:
    config:
      profile: test
      label: develop
      name: dg-spring-boot-admin
      discovery:
        service-id: dg-spring-config
  rabbitmq:
    host: 192.168.11.159
    port: 5672
    username: guest
    password: guest
