spring:
  application:
    name: dg-spring-boot-admin
  profiles:
    active: local
  cloud:
    config:
      profile: local
      label: develop
      discovery:
        enabled: true
        service-id: dg-spring-config
