server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  server:
    # 是否开启自我保护（正式环境需要开启）
    enable-self-preservation: false
    # 3秒自动剔除失效节点
    eviction-interval-timer-in-ms: 3000
    # eureka service 刷新 readCacheMap 时间
    response-cache-update-interval-ms: 3000
  client:
    #注册自己
    register-with-eureka: false
    # 是否需要从其他eureka 获取注册表信息
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    metadata-map:
      management:
        context-path: ${server.servlet.context-path:${SERVER_CONTEXTPATH:}}${management.context-path:${MANAGEMENT_CONTEXTPATH:}}
    statusPageUrlPath: ${server.servlet.context-path:${SERVER_CONTEXTPATH:}}${management.context-path:${MANAGEMENT_CONTEXTPATH:}}${endpoints.info.path:/swagger-ui.html}
    healthCheckUrlPath: ${server.servlet.context-path:${SERVER_CONTEXTPATH:}}${management.context-path:${MANAGEMENT_CONTEXTPATH:}}${endpoints.health.path:/health}
    management:
      port: ${management.port:${MANAGEMENT_PORT:${server.port:${SERVER_PORT:9000}}}}
    lease-expiration-duration-in-seconds: 90