server:
  port: 8761
spring:
  application:
    name: dg-eureka

  # 初期先使用用本地配置文件，稳定以后采用 config
  cloud:
    config:
      uri: http://127.0.0.1:8888/
      profile: test
      label: develop
      name: dg-eureka
  rabbitmq:
    host: 192.168.11.159
    port: 5672
    username: guest
    password: guest
