spring:
  application:
    name: dg-eureka
  profiles:
    active: local
  cloud:
    config:
      enabled: true
      label: develop
      profile: local
      uri: http://192.168.11.159:8888/
server:
  port: 8761