spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jasonhls/dg-config-repo.git
          username: Jasonhls
          password: 13367258287hls
          search-paths: /**
  rabbitmq:
    host: 192.168.11.159
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always