server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: http://192.168.11.161:81/dg-mall/dg-config-repo.git
          search-paths: /**  # 指定搜索路径，如果有多个路径则使用,分隔
          username: hels
          password: Jasonhls123
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
